# Generated by Django 3.0.8 on 2020-09-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='website',
        ),
    ]
