# Generated by Django 3.0.8 on 2020-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuserprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
