# Generated by Django 3.0.8 on 2020-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200927_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank='True', default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, default='https://ringwooddental.com.au/wp-content/uploads/2018/05/profile-placeholder-f-e1526434202694.jpg', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank='True', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.DeleteModel(
            name='CustomUserProfile',
        ),
    ]
