# Generated by Django 3.0.8 on 2020-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200926_1914'),
        ('users', '0011_auto_20200927_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(blank=True, default='', to='projects.Skill'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
