# Generated by Django 3.0.8 on 2020-09-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200927_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),

        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
