# Generated by Django 3.0.8 on 2020-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200928_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='https://via.placeholder.com/728x90.png?text=Website+coming+soon', verbose_name='Website'),
        ),
    ]
