# Generated by Django 3.0.8 on 2020-09-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200926_1914'),
        ('users', '0021_auto_20200928_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='projects.Skill'),
        ),
    ]
