# Generated by Django 3.0.8 on 2020-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200929_1509'),
        ('users', '0023_auto_20200929_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pledges',
            field=models.ManyToManyField(to='projects.Pledge'),
        ),
    ]
