# Generated by Django 3.0.8 on 2020-09-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_pledges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pledges',
        ),
    ]
