# Generated by Django 3.0.8 on 2020-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200929_1509'),
        ('users', '0028_auto_20200929_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills_p',
            field=models.ManyToManyField(blank=True, to='projects.Skill'),
        ),
    ]
