# Generated by Django 3.0.8 on 2020-10-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_skills_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills_p',
            new_name='skills',
        ),
    ]
