# Generated by Django 3.0.8 on 2020-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200929_1509'),
        ('users', '0031_remove_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.Skill'),
        ),
    ]
