# Generated by Django 3.0.8 on 2020-10-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
    ]
