# Generated by Django 3.0.8 on 2020-08-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='supporter',
        ),
    ]
