# Generated by Django 3.0.8 on 2020-09-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200830_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='volunteer',
            new_name='owner',
        ),
    ]
