# Generated by Django 3.0.8 on 2020-09-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200920_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='owner',
            new_name='volunteer',
        ),
    ]
