# Generated by Django 3.0.8 on 2020-09-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200920_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='volunteer',
            new_name='owner',
        ),
    ]
