# Generated by Django 3.0.8 on 2020-09-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200920_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledge',
            options={'ordering': ['id']},
        ),
    ]
