# Generated by Django 3.0.8 on 2020-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200920_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default='https://picsum.photos/301'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.URLField(default='https://picsum.photos/311'),
            preserve_default=False,
        ),
    ]
