# Generated by Django 3.0.8 on 2020-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200929_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='skill',
            field=models.ManyToManyField(help_text='Select a skill for this project', related_name='pledges', to='projects.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this project', related_name='projects', to='projects.Category'),
        ),
    ]
